---
- name: Configurar perfil de Web Filter en FortiGate
  hosts: fortigate
  connection: httpapi
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"
  tasks:
  - name: Crear perfil Web Filter bloqueando categoría 29
      fortios_webfilter_profile:
        state: "present"
        webfilter_profile:
          name: "Bloqueo_Cat_29"
          comment: "Bloqueo de categoría General Interest - Personal"
          ftgd_wf:
            filters:
              - id: 29
                action: block
          options:
            https_replacemsg: enable
            inspection_mode: proxy
            log_all_url: enable
